# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934e7dd56f938fed48e54d17a65ce2db71e9e827eeda7c26442b6c624460f406a10a54ec3399ece32174ec4160f28125e65d24b99ba17d9ca9aa65a17fa83c6c

test:
  secret_key_base: 0fc0b6bc4ef08002d2d1facd7b46ac2d4efd4953f2873bb5baf31f6ccd81c1f0a27275063388f8d379db5000568eaac980ae0ba083c97a92420c6c9644f2d65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
