# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693150a4346b2ce1c75d8a451bdd392f036b27a50399c2b6727cf86da72200afcebce5f0ae5638a7652b1534434db6f4d0392fc834b29d8e97794c91922fde54

test:
  secret_key_base: ae1672a6946074d1093cff8215e4ba2ec0dd8063453f56a151afe04ea7a2e02255768ed58f121feb6181f87877286349b11bc20f7e4fa0bb234bb63dcb5cbdb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
